#!/bin/bash

# Multi-Site Environment Switcher for Eventz
# Usage: ./scripts/switch-env.sh <site-name>
# Example: ./scripts/switch-env.sh tdd-peru

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Get the site name from argument
SITE_NAME=$1

if [ -z "$SITE_NAME" ]; then
    echo -e "${RED}Error: Site name is required${NC}"
    echo "Usage: ./scripts/switch-env.sh <site-name>"
    echo ""
    echo "Available sites:"
    echo "  - tdd-peru"
    echo "  - tdd-talk-prod"
    exit 1
fi

# Define site configurations
declare -A SITES

# TDD Peru Configuration
SITES[tdd-peru.project_id]="tdd-peru"
SITES[tdd-peru.api_key]="AIzaSyBCDzPxBp24_7WPXCB58jR-Iu1I6gJDqzI"
SITES[tdd-peru.auth_domain]="tdd-peru.firebaseapp.com"
SITES[tdd-peru.storage_bucket]="tdd-peru.firebasestorage.app"
SITES[tdd-peru.messaging_sender_id]="1098458079681"
SITES[tdd-peru.app_id]="1:1098458079681:web:03d2b45c4fe5dd3383cf40"
SITES[tdd-peru.admin_wallet]="0xc2564e41B7F5Cb66d2d99466450CfebcE9e8228f"

# TDD Talk Configuration
SITES[tdd-talk-prod.project_id]="tdd-talk-prod"
SITES[tdd-talk-prod.api_key]="AIzaSyDWcuZz1cc6J9wTAyeUH6ObKTZd6pMY234"
SITES[tdd-talk-prod.auth_domain]="tdd-talk-prod.firebaseapp.com"
SITES[tdd-talk-prod.storage_bucket]="tdd-talk-prod.firebasestorage.app"
SITES[tdd-talk-prod.messaging_sender_id]="468423336143"
SITES[tdd-talk-prod.app_id]="1:468423336143:web:6b98b0632cd43dd84217ba"
SITES[tdd-talk-prod.admin_wallet]="0xc2564e41B7F5Cb66d2d99466450CfebcE9e8228f"

# Check if site exists
if [ -z "${SITES[$SITE_NAME.project_id]}" ]; then
    echo -e "${RED}Error: Unknown site '$SITE_NAME'${NC}"
    echo ""
    echo "Available sites:"
    echo "  - tdd-peru"
    echo "  - tdd-talk-prod"
    exit 1
fi

echo -e "${YELLOW}🔄 Switching to site: $SITE_NAME${NC}"
echo ""

# Get configuration for selected site
PROJECT_ID="${SITES[$SITE_NAME.project_id]}"
API_KEY="${SITES[$SITE_NAME.api_key]}"
AUTH_DOMAIN="${SITES[$SITE_NAME.auth_domain]}"
STORAGE_BUCKET="${SITES[$SITE_NAME.storage_bucket]}"
MESSAGING_SENDER_ID="${SITES[$SITE_NAME.messaging_sender_id]}"
APP_ID="${SITES[$SITE_NAME.app_id]}"
ADMIN_WALLET="${SITES[$SITE_NAME.admin_wallet]}"

# 1. Update .env file
echo -e "${GREEN}✓${NC} Updating .env file..."
cat > .env << EOF
# Firebase Configuration - Active Site: $SITE_NAME
# Auto-generated by switch-env.sh on $(date)

NEXT_PUBLIC_FIREBASE_API_KEY=$API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID=$APP_ID

# WalletConnect / Reown AppKit Configuration
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=d15114286aee1ad0e87799c4eea8287d

# Admin Wallet Address (must match to access admin area)
NEXT_PUBLIC_ADMIN_WALLET_ADDRESS=$ADMIN_WALLET
EOF

# 2. Update .firebaserc
echo -e "${GREEN}✓${NC} Updating .firebaserc..."
cat > .firebaserc << EOF
{
  "projects": {
    "default": "$PROJECT_ID"
  }
}
EOF

# 3. Update firebase.json storage bucket
echo -e "${GREEN}✓${NC} Updating firebase.json..."
cat > firebase.json << EOF
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "storage": [
    {
      "bucket": "$STORAGE_BUCKET",
      "rules": "storage.rules"
    }
  ]
}
EOF

# 4. Switch Firebase CLI project
echo -e "${GREEN}✓${NC} Switching Firebase CLI project..."
firebase use "$PROJECT_ID" > /dev/null 2>&1

echo ""
echo -e "${GREEN}✅ Successfully switched to $SITE_NAME${NC}"
echo ""
echo "Configuration:"
echo "  Project ID: $PROJECT_ID"
echo "  Storage Bucket: $STORAGE_BUCKET"
echo "  Admin Wallet: $ADMIN_WALLET"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Verify configuration: npm run verify-env"
echo "  2. Start dev server: npm run dev"
echo "  3. Deploy to Firebase: npm run deploy:$SITE_NAME"
